### ISSUE TITLE
XMLValidator is using system out to print errors.

### ISSUE THREAD

**Issue by iservecharlie** [iservecharlie/LynxKikApi#7]
Replace with the logging framework used.

refer to how other classes are handling Logging. e.g. org.kik.bot.core.KikClient

**Comment by priyankalakhe** [comment]
@iservecharlie  - I can take a look at this issue. 

As part of this, I plan on 
1. changing the 1 occurence of `System.out` to using `org.apache.log4j.Logger`
2. replace the `e.printStackTrace()` methods with the `logger.error()` as well

Do let me know if that's ok and I can send out a PR

**Comment by iservecharlie** [comment]
Sounds good. Feel free to open a PR and i can review and merge it as soon as I can. Thank you.

**Comment by priyankalakhe** [comment]
@iservecharlie - https://github.com/iservecharlie/LynxKikApi/pull/8
